Fixed imports and code for AutoMLx 23.4.1v notebooks
oracle-samples/oci-data-science-ai-samples pull request #386
Opened 2024-01-12 18:14 UTC by dipatidar

2024-01-12 18:20 UTC, darenr commented
This is not backward compatible, for people that use the existing conda packs it'll break.

rather than 

```
import automlx
```

the suggestion was to do

```
try:
  import automlx
except ModuleNotFoundError:
  import automl
```

something like that so older conda packs will continue to work with the refreshed notebooks

2024-01-29 23:06 UTC, dipatidar commented
The notebook runs fails on existing code with new automlx import. It required code modification in notebook for some features.

2024-01-30 16:27 UTC, darenr requested changes
The notebooks should be changed to be compatible with both old and new module name, rather than

`import automlx`

which will only work on the latest version it should try/except and alias to a common name. 

Also why both `import automlx` and then `from automlx import init`?

2024-01-31 02:03 UTC, smith-kyle commented
Just a heads up, you can review notebook changes like this using [GitNotebooks](https://gitnotebooks.com).

e.g. this pull request [https://gitnotebooks.com/oracle-samples/oci-data-science-ai-samples/pull/386](https://gitnotebooks.com/oracle-samples/oci-data-science-ai-samples/pull/386)

It's free for public repos, so might be helpful for y'all.

2025-04-13 18:20 UTC, mrDzurb commented
Hi @dipatidar what is the status of this PR? I see in user channels a few reports about the same problem. One customer opened SEV3 ticket for this.

2025-04-14 22:41 UTC, darenr approved these changes

2025-04-15 00:16 UTC, mrDzurb approved these changes

2025-04-15 00:16 UTC, merged