Updated README for NIM Model Deployment
oracle-samples/oci-data-science-ai-samples pull request #478
Opened 2024-08-21 09:43 UTC by Gaurav141199

README for NIM Model Deployment to include use of Model Catalog and Model-by-reference.

2024-08-21 10:17 UTC, gargnipungarg commented on model-deployment/containers/nim/README.md
> +* Utilising Model Catalog to store Models in OCI, later used for model deployment
Add hyperlink here to the readme ./Readme-model-catalog.md

2024-08-21 10:18 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +Once you built and pushed the NIM container, you can now use the `Bring Your Own Container` Deployment in OCI Data Science to deploy the Llama3 model.
No built

2024-08-21 10:18 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +Follow the steps mentioned [here][https://github.com/oracle-samples/oci-data-science-ai-samples/blob/main/model-deployment/containers/llama2/README.md], refer the section One time download to OCI Mod
this is not hyperlink code
[]()

2024-08-21 10:18 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +Follow the steps to upload your model to Object Storage [here][https://github.com/oracle-samples/oci-data-science-ai-samples/blob/main/LLM/llama3.1-8B-deployment-vLLM-container.md]
fix hyperlinks

2024-08-21 10:19 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +        * Key: `SHM_SIZE`, Value: `5g`
Did you need it? If not, you can remove

2024-08-21 10:45 UTC, gargnipungarg requested changes

2024-08-21 10:45 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +* Pull the latest NIM Image to local machine or through NB session. Tag it with desired name.
We cant pull image using NB session

2024-08-21 10:45 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +* Pull the latest NIM Image to local machine or through NB session. Tag it with desired name.
call download on workstation

2024-08-21 10:45 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +Follow the steps mentioned [here](https://github.com/oracle-samples/oci-data-science-ai-samples/blob/main/model-deployment/containers/llama2/README.md), refer the section One time download to OCI Mod
We discussed adding specific sections Gaurav
You need to add hyperlink to the section, not the whole readme page

2024-08-21 10:45 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +Utilise the [section](https://github.com/oracle-samples/oci-data-science-ai-samples/blob/main/LLM/llama3.1-8B-deployment-vLLM-container.md) on Create Model by Reference using ADS to create the model.
same here

2024-08-21 10:45 UTC, gargnipungarg commented on model-deployment/containers/nim/README.md
> +Once NIM container is pushed, you can now use the `Bring Your Own Container` Deployment in OCI Data Science to deploy the Llama3 model.
here we are building and pushing
my comment for removing build was only other Readme

2024-08-21 10:45 UTC, gargnipungarg commented on model-deployment/containers/nim/README-MODEL-CATALOG.md
> +* Utilising Model-by-reference Feature to download model
We cant call it model by reference. External customers cant understand this.
Use Object storage to store the model and creating a model catalog pointing to Object storage bucket

2024-08-28 05:21 UTC, gargnipungarg approved these changes

2024-08-28 14:25 UTC, liudmylaru approved these changes

2024-08-28 14:26 UTC, merged